spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./app.db;AUTO_SERVER=TRUE
    username: sa
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  sql:
    init:
      mode: always
server:
  port: 8080